version: "3"
services:
  node:
    container_name: node-azure_static
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    ports:
      - 8080:8080
    init: true
    tty: true


  
