name: Node-CI

on: 
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci
      # temporarily disabling for the move to NextJS - no testing yet
      # - run: npm test -a
      - run: npm run build
